### ISSUE TITLE
Keep MQTT connection alive

### ISSUE THREAD

**Issue by schmurtzm** [couin3/RFLink#10]
MQTTClient.loop();  in 6_WiFi_MQTT.cpp file must be uncommented to keep MQTT connection alive.
[This simple example](https://github.com/knolleary/pubsubclient/blob/master/examples/mqtt_basic/mqtt_basic.ino) from pubSubClient can be used. 

I suggest to execute MQTTClient.loop(); all the time outside of any test.

Something like that :

```
void publishMsg()
{
  if (!MQTTClient.connected())
  {
    reconnect();
  }
  MQTTClient.loop();

  if (MQTTbuffer[0] != 0)
  {
    MQTTClient.publish(MQTT_TOPIC_OUT, MQTTbuffer);
    MQTTbuffer[0] = 0;
  }
}
```

**Comment by couin3** [comment]
Here is an implementation b5b0745.
I want to avoid spamming MQTTClient.loop(); so here is a time limit set in MQTT_LOOP_MS.
On my setup, 10s is a maximum if you don't want any reconnect message.

**Comment by schmurtzm** [comment]
Seems OK to me : no more disconnection.
