### ISSUE TITLE
Problem with the Plugin 001 optimization

### ISSUE THREAD

**Issue by schmurtzm** [couin3/RFLink#15]
I remark that the commit "Plugin 001 optimization …" has a very bad influence on protocoles 005,061 and 062.

This test :
if ((Plugin_id[x] == 1) || ((Plugin_id[x] != 0) && (Plugin_id[x] >= RawSignal.Pulses[0])))
not happens often so most of messages are lost.

**Comment by couin3** [comment]
We came to the same conclusion...
RawSignal.Pulses[0] is more complex than I thought.
Rollback done 14dcfb0

**Comment by couin3** [comment]
Closing if no one encounters issues anymore
