### ISSUE TITLE
wrong define in plugin 047c

### ISSUE THREAD

**Issue by zoomx** [couin3/RFLink#20]
In plugin 047c line 108

         if (RawSignal.Pulses[x] > LACROSSE43_PULSEMINMAX)

should be

         if (RawSignal.Pulses[x] > AURIOLV4_PULSEMINMAX

otherwise when lacrosse plugin 002c is commented out it doesn't compile.

**Comment by couin3** [comment]
Change done on branches master, V2.0, V3.0 and V4.0

By the way, the "right" setting is far more restrictive :
#define LACROSSE43_PULSEMINMAX 576 / RAWSIGNAL_SAMPLE_RATE 
#define AURIOLV4_PULSEMINMAX 352 / RAWSIGNAL_SAMPLE_RATE

So, tell me if it still works fine or whether we need to relax it too.

**Comment by couin3** [comment]
Let's close that one for now!
