### ISSUE TITLE
Add MQTT to Serial working plugins

### ISSUE THREAD

**Issue by couin3** [couin3/RFLink#9]
Linked to #8 list.
This is a time consuming, boring yet needed task.
In short, adding MQTTBuffer handling in each known good plugins.
Plugin 004, NewKaku, can be used as an example.

**Comment by schmurtzm** [comment]
Done on 061 and 062. Pull request also done.

**Comment by schmurtzm** [comment]
Done on 005

**Comment by couin3** [comment]
All R29 working plugins done. closing
